module GameConstants
  FIELD_WIDTH = 110
  FIELD_HEIGHT = 25
  FIELD_WIDTH_GAMING = FIELD_WIDTH - 2
  FIELD_HEIGHT_GAMING = FIELD_HEIGHT - 2
  BARRIERS_COUNT = 30
  APPLE_COUNT = 30
  SIZE_PYTHON = 6
end